### ISSUE TITLE
remove PHP 7.4 support after mezzio 3.12 in Admin V4

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-admin#126]
composer.json
"php": "~7.4.0 || ~8.0.0 || ~8.1.0",    -> "php": "~8.0.0 || ~8.1.0 || ~8.2.0",

"mezzio/mezzio": "^3.11.0", ->  "mezzio/mezzio": "^3.13.0",

**Comment by marioradu05** [comment]
Dropped support for PHP 7.4 in https://github.com/dotkernel/admin/issues/131. The only remaining things here are to update mezzio/mezzio to 3.13.0 and add support for PHP 8.2.0.
