### ISSUE TITLE
AdminLogin entity has unneeded unique restrictions on $identity and $adminIp

### ISSUE THREAD

**Issue by OnitaAndrei** [dotkernel/dot-admin#136]
a second login of the same identity or ip as a previous one will throw an error due to a unique restriction on those columns

**Comment by marioradu05** [comment]
@OnitaAndrei please provide more details on this issue.

**Comment by alexmerlin** [comment]
@OnitaAndrei: it looks like this issue was fixed in #137 
If so, please close this ticket with a reference to the PR that fixed it.

**Comment by OnitaAndrei** [comment]
fixed in #137
