### ISSUE TITLE
Update NPM packages

### ISSUE THREAD

**Issue by marioradu05** [dotkernel/dot-admin#157]
Please take a look at the NPM packages and update them if needed.

The goal is for the packages to work with the latest versions of node & npm, if possible.

**Comment by arhimede** [comment]
@mada27  please take a look at this one

**Comment by arhimede** [comment]
Bootsrap 4 is out of support, EOL 
https://github.com/twbs/release

https://datatables.net/examples/styling/bootstrap5.html

@mada27

**Comment by arhimede** [comment]
fixed in #175
