### ISSUE TITLE
Bump to PHP 8.3

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-admin#198]

**Comment by bidi47** [comment]
blocked by 3rd party packages
    - roave/psr-container-doctrine 4.1.0 requires psr/cache ^2.0.0 || ^3.0.0 -> satisfiable by psr/cache[2.0.0, 3.0.0].
    - laminas/laminas-cache[3.12.0, ..., 3.12.1] require psr/cache ^1.0 -> satisfiable by psr/cache[1.0.0, 1.0.1].

roave/psr-container-doctrine v4.1.0 is required for PHP 8.3
laminas/laminas-cache has a new milestone in the works to update the psr/cache dependency
https://github.com/laminas/laminas-cache/milestone/11

also see
https://github.com/laminas/laminas-cache/issues/133
https://github.com/laminas/laminas-cache/pull/196
https://github.com/laminas/laminas-cache/pull/214

**Comment by arhimede** [comment]
https://github.com/laminas/laminas-cache/issues/292

> there wont be support for newer psr/cache majors in v3 of laminas-cache.
There will be v4 of laminas-cache at some point in time which adds support for newer versions of psr/cache.
There are no ETAs and there is no current effort in finishing v4 milestone in the near future.

**Comment by bidi47** [comment]
a solution is being investigated here
https://github.com/dotkernel/dot-twigrenderer/issues/37

**Comment by bidi47** [comment]
solved in
https://github.com/dotkernel/admin/pull/218
https://github.com/dotkernel/admin/pull/220
