### ISSUE TITLE
doctrine/cache sunset // find replacement

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-admin#217]
we are cache-ing the doctrine stuff using the code , in local.php

`             'orm_default' => [
                // it is recommended to disable doctrine cache on development
                // just comment any type of cache you don't want to be applied on development
                'query_cache'    => PhpFileCache::class,
                'metadata_cache' => PhpFileCache::class,
                'result_cache'   => PhpFileCache::class,
`

and we recommend the following cache policy:
 https://www.dotkernel.com/how-to/doctrine-cache-in-mezzio-and-dotkernel/

Now, the problem is that the function `PhpFileCache`  does not exists anymore 
we need to replace it somehow ..

maybe dot-cache ressurected ?

**Comment by arhimede** [comment]
Option 1: to use symfony cache 
https://www.doctrine-project.org/projects/doctrine-orm/en/2.17/reference/caching.html

**Comment by arhimede** [comment]
Option 2:
extend dot-cache with the missing functions

**Comment by arhimede** [comment]
let's analyse this package too 
https://github.com/PHPSocialNetwork/phpfastcache

**Comment by arhimede** [comment]
this is an example of symfony/cache implementation 
https://github.com/Casilium/casilium/commit/12bf0854ad8ac8e9b88764cf79a3c0dd584d1513

we should investigate if we use this in dotkernel/dot-cache or directly

**Comment by arhimede** [comment]
https://www.dotkernel.com/dotkernel/doctrine-cache-using-symfony-cache/

@OnitaAndrei  please test

**Comment by OnitaAndrei** [comment]
Tested and works just fine

**Comment by arhimede** [comment]
@bidi47  pelase test in the API if it is working

**Comment by bidi47** [comment]
solved in https://github.com/dotkernel/api/pull/227

**Comment by arhimede** [comment]
![Image](https://github.com/dotkernel/admin/assets/22009710/220e166d-aba8-4b28-b8a9-97e3b3c47834)

**Comment by arhimede** [comment]
why access and modify are 1 true year ahead ?

**Comment by alexmerlin** [comment]
### Short answer
If there is no default lifetime configured, Symfony Cache [touch](https://www.php.net/touch)es the cached item it just created and sets its modification time to +1 year in the future.

By setting `default_life_time` in `config/autoload/doctrine.global.php` under `doctrine`->`cache`->`filesystem`, we can control the cache items' expiration time (which, will still be set to the future). The below example sets default lifetime to 86400 seconds (=1 day) (file mtime will be today + 1 day):
```php

return [
    'doctrine' => [
        'cache' => [
            'filesystem' => [
                'class' => FilesystemAdapter::class,
                'directory' => getcwd() . '/data/cache',
                'namespace' => 'doctrine',
                'default_life_time' => 86400,
            ],
        ],
    ],
];
```


### Long answer
When Doctrine's EntityManager tries to load metadata for an entity, `vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php`->`getMetadataFor` is executed. If no metadata was found in the cache, the entity metadata is read and saved to the cache by calling `$this->cache->commit();`.
After jumping through a couple of interface implementations, the cache is finally written at:
[symfony/cache/Traits/FilesystemCommonTrait.php:106](https://github.com/symfony/cache/blob/7.0/Traits/FilesystemCommonTrait.php#L106) where, after write is complete, the following code is executed
```php
touch($tmp, $expiresAt ?: time() + 31556952); // 1 year in seconds
```
adding 1 year to the cache file's modification time.


If someone is interested, I traced the steps to follow the request:

- https://github.com/doctrine/orm/blob/3.1.x/src/EntityManager.php#L215
- https://github.com/doctrine/persistence/blob/3.3.x/src/Persistence/Mapping/AbstractClassMetadataFactory.php#L175
- https://github.com/doctrine/persistence/blob/3.3.x/src/Persistence/Mapping/AbstractClassMetadataFactory.php#L201
- https://github.com/doctrine/persistence/blob/3.3.x/src/Persistence/Mapping/AbstractClassMetadataFactory.php#L222
- https://github.com/symfony/cache/blob/7.0/Adapter/AbstractAdapter.php#L131
- https://github.com/symfony/cache/blob/7.0/Adapter/AbstractAdapter.php#L147
- https://github.com/symfony/cache/blob/7.0/Traits/FilesystemTrait.php#L83
- https://github.com/symfony/cache/blob/7.0/Traits/FilesystemTrait.php#L89
- https://github.com/symfony/cache/blob/7.0/Traits/FilesystemCommonTrait.php#L85
- https://github.com/symfony/cache/blob/7.0/Traits/FilesystemCommonTrait.php#L106

**Comment by arhimede** [comment]
In conclusion, we will not add the doctrine configuration key:

'default_life_time' => 86400,
