### ISSUE TITLE
psr-container-doctrine upgrating makes application crash. config key missing

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-admin#262]
With a simple composer update, application is crashing because of newst version of prs-container-doctrine (5.2.1)

typed_field_mapper => null 

This needed to be added in the config/autoload/doctrine.global.php config

**Comment by pinclau** [comment]
the issue was with psr-container-doctrine, 5.2.1 was corrupted, in 5.2.2 was fixed, but i added the key in #263  just in case
