### ISSUE TITLE
improve dashboard

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-admin#288]
instead or above monthly stats demo box 
a box with few links:
- to github repo 
- to dotkernel.com
- to documentation

**Comment by alexmerlin** [comment]
@arhimede what do you think of the new `Dotkernel Links` box?

![image](https://github.com/user-attachments/assets/e1c53f73-bdec-4157-bcca-8ba143626047)

**Comment by arhimede** [comment]
perfect !
