### ISSUE TITLE
uuid related: Could not convert database value  to Doctrine Type uuid_binary_ordered_time.

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-admin#60]
Current **ramsey/uuid:4.1.0** ERROR
"message":"An exception has been thrown during the rendering of a template (\"Could not convert database value \"11eadd26-efe4-58ba-b...\" to Doctrine Type uuid_binary_ordered_time. Expected format: UuidV1\").","extra":{"\u0000Twig\\Error\\Error\u0000lineno":57,"\u0000Twig\\Error\\Error\u0000name":"@partial/account-menu.html.twig",

Temporary solution : 
`composer require ramsey/uuid:4.0.1`

**Comment by arhimede** [comment]
Related to this issue:
https://github.com/ramsey/uuid/issues/327

**Comment by 537mfb** [comment]
@arhimede Have you tried my workaround at ramsey/uuid#329?
 
Id like to know if it works for other people with similar issue

**Comment by arhimede** [comment]
@537mfb Yes, your workaround worked. 
we implemented it a bit more general//abstract

https://github.com/dotkernel/admin/pull/61/files
