### ISSUE TITLE
laminas form

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-admin#93]
1. check if the package laminas/laminas-form is required 
2.  if can be removed from composer, remove it 
3. make a new release with the updated composer.json file 
4. trebe sa dam la baietii noul composer sa stie gen

**Comment by bidi47** [comment]
laminas form is removed
checking other laminas, mezzio packages that can be removed from the root composer.json

**Comment by bidi47** [comment]
updated function declarations that returned an issue as a result of the update discussed in https://github.com/dotkernel/frontend/issues/249

the update is included in the existing open pull request
https://github.com/dotkernel/frontend/pull/251
