### ISSUE TITLE
missing variable in local.php

### ISSUE THREAD

**Issue by bidi47** [dotkernel/dot-admin#96]
in _config/autoload/local.php_ (also _local.php.dist_) the variable _$app_ is used, but not defined
what structure should it have, besides _$app['name']_?
or could it be simply replaced with a string?

**Comment by alexmerlin** [comment]
The variable `$app` is defined, but in a different config file: `config/autoload/app.global.php`.

**Comment by bidi47** [comment]
is reported it because the editor highlighted the missing variable as as error
but as long as it causes no execution errors, the issue can be closed
